# Generated by Django 4.1.7 on 2023-03-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurmalar', 'verbose_name_plural': 'Buyurmalar'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Buyurmalar', 'verbose_name_plural': 'Buyurmalar'},
        ),
    ]
