# Generated by Django 4.1.7 on 2023-03-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_order_options_alter_phone_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtmalar', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Tovarlar', 'verbose_name_plural': 'Tovarlar'},
        ),
    ]
