# Generated by Django 4.1.7 on 2023-03-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_order_options_alter_phone_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Rasmi'),
        ),
    ]
