# Generated by Django 4.1.7 on 2023-03-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_phone_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasmi'),
        ),
    ]
