# Generated by Django 4.1.7 on 2023-03-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_passport_alter_order_selfie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(max_length=500, null=True, upload_to='', verbose_name='Kelishuv'),
        ),
    ]
