# Generated by Django 4.1.7 on 2023-03-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(max_length=500, null=True, upload_to='docs/%Y/%m/%d/', verbose_name='Kelishuv'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nomi'),
        ),
    ]
